spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://localhost:3306/kongxsh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 输出SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出SQL日志
  mapper-locations: classpath:/mapper/**/*.xml  # XML映射文件位置（如果用XML）

server:
  port: 9527
  servlet:
    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    com.demo: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"


